import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { PhotoStorage } from "./photo-storage";

/** Stores photos as files under one root folder (a Docker volume in production). */
export class LocalPhotoStorage implements PhotoStorage {
  constructor(private readonly root: string) {}

  async put(key: string, data: Buffer) {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, data);
  }

  get(key: string) {
    return readFile(this.pathFor(key));
  }

  async delete(key: string) {
    await rm(this.pathFor(key), { force: true });
  }

  /** Keys are generated by the server, but never let one escape the root folder. */
  private pathFor(key: string) {
    const path = resolve(join(this.root, key));
    const inside = relative(this.root, path);
    if (inside.startsWith("..") || resolve(inside) === inside) {
      throw new Error("Invalid photo key");
    }
    return path;
  }
}
